server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://hk3cvdv00649.oocl.com:5678/production
    username: root
    password: IntelligentCat003
  http:
    encoding:
      force: true
  jpa:
    hibernate:
      ddl-auto: none